// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-GZx6sb2JatLkbGA9vSqnOggAxLD9xbU',
    appId: '1:857836391410:web:f1ccc935237f80eaccf96b',
    messagingSenderId: '857836391410',
    projectId: 'autoservice-48c34',
    authDomain: 'autoservice-48c34.firebaseapp.com',
    storageBucket: 'autoservice-48c34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-uc4TsbumUPP8Z6jAgZwn1-ddBSGc3Qc',
    appId: '1:857836391410:android:5ec9c61127f97e49ccf96b',
    messagingSenderId: '857836391410',
    projectId: 'autoservice-48c34',
    storageBucket: 'autoservice-48c34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJpqkGfdUO-Y2P4MF_72ig-sIoYmjSUBI',
    appId: '1:857836391410:ios:d018a59a3a515f22ccf96b',
    messagingSenderId: '857836391410',
    projectId: 'autoservice-48c34',
    storageBucket: 'autoservice-48c34.firebasestorage.app',
    iosBundleId: 'com.example.autoServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJpqkGfdUO-Y2P4MF_72ig-sIoYmjSUBI',
    appId: '1:857836391410:ios:d018a59a3a515f22ccf96b',
    messagingSenderId: '857836391410',
    projectId: 'autoservice-48c34',
    storageBucket: 'autoservice-48c34.firebasestorage.app',
    iosBundleId: 'com.example.autoServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-GZx6sb2JatLkbGA9vSqnOggAxLD9xbU',
    appId: '1:857836391410:web:5e85ab08fae47aefccf96b',
    messagingSenderId: '857836391410',
    projectId: 'autoservice-48c34',
    authDomain: 'autoservice-48c34.firebaseapp.com',
    storageBucket: 'autoservice-48c34.firebasestorage.app',
  );
}
